### PR TITLE
Get data from model API

### LINKED ISSUE #23: Get calculated variables from REST API
Zentracloud has an API endpoint for calculated variables like plant-available water and evapotranspiration.  Need to access this and add to our dataset.

### PR DESCRIPTION
**Pull request by Aariq**
This PR adds a function, `gsi_get_eto()`, and code that runs it to the main scheduled .Rmd document to get ETo data from the ZentraCloud models API endpoint and wrangle it into a separate .csv file that is written to the Box folder.

### CODE REVIEW

**Comment by UArizonaCampusLivingLabforGSI** [comment]
- I think having the environmental variables be daily instead of hourly is sufficient.
- That is a bit of a bummer that ETo does not allow greater than a month. I am not sure what to do or how to proceed with that.
- I will update this in the site_info and metadata documents. All ATMOS are at about 2M. We will gather that information and include the exact values soo as well. For now, I think 2 m is good.

Gould Simpson z6-20761 : Lat: 32.2294203 Long: -110.955557 Elevation: 746 m
Old Main z6-19484: Lat: 32.231622 Long: -110.9537758 Elevation: 735 m
PAS  z6-20762 : Lat: 32.2294215 Long: -110.9541533 Elevation: 741 m

**Comment by Aariq** [comment]
Should we maybe just add this information to site_info.csv on box?  Also, I don't see plant-available water as an option from the API and I recall that being one of the plots on the ZentraCloud dashboard you were interested in re-creating.  The only options from the API appear to be ETo and ETr.

**Comment by UArizonaCampusLivingLabforGSI** [comment]
I updated the site_info spreadsheet in Box with the lat/long/elevation information. I did notice that we already have height for the ATMOS included in the sensor height depth column. It is not exact but is close enough for use. 

I am not sure why we can not pull PAW but will look to see if there is a setting issue that is limiting data to ETo ETr

**Comment by Aariq** [comment]
I've just published this new version of the scheduled workflow on Posit Connect, but I'll wait for it to run once or twice and check the results before merging this PR.

**Comment by Aariq** [comment]
Hmm, looks like some sensor x date combinations have more than one value for ETo in the file on Box.  Need to figure out how to deal with this still.

**Comment by UArizonaCampusLivingLabforGSI** [comment]
Zentra tech confirmed that ETo/ETr are the only models available right now and does not have a timeline on if/when others will be available.

**Pull request merged**
